import streamlit as st
import pandas as pd
from functions_page import getbranch_code, getcutoff_rank, getcollege_code, gettable, generate_pdf_table

# File paths
FILE_PATH1 = "cet_colg_data.xlsx"

@st.cache_data
def load_excel_file(FILE_PATH):
    """Load Excel file."""
    try:
        data = pd.read_excel(FILE_PATH, engine="openpyxl")
        data.columns = data.columns.str.strip()  # Clean column names
        return data
    except Exception as e:
        st.error(f"Error loading file: {e}")
        return None

df = load_excel_file(FILE_PATH1)

# # Disclaimer section
# def display_disclaimer():
#     st.warning("""
#     **Disclaimer**:
#     1. The results generated by this app are based on the previous year's cutoff data and are only indicative.
#     2. Actual seat allocation during K-CET counselling depends on your real-time choices and preferences.
#     3. The cutoff ranks are dynamic and may change yearly based on factors such as seat availability and the number of candidates.
#     4. This app is a guidance tool, and users are advised to cross-verify the information with official sources.
#     5. The developers are not responsible for decisions made based on this app.

#     Please acknowledge this disclaimer before proceeding.
#     """)

#     if st.button("I Acknowledge", key="acknowledge_button"):
#         st.session_state["disclaimer_acknowledged"] = True

# # Initialize session state for disclaimer
# if "disclaimer_acknowledged" not in st.session_state:
#     st.session_state["disclaimer_acknowledged"] = False

# if not st.session_state["disclaimer_acknowledged"]:
#     display_disclaimer()
#     st.stop()

# Title and introduction
st.title("K-CET Counselling Helper 🎓")
st.write("### Efficient College and Branch Comparison Tool")

# Initialize session state
if "selected_data" not in st.session_state:
    st.session_state["selected_data"] = []

# Dropdown setup
col1, col2, col3 = st.columns(3)
with col1:
    exclusion_list = ["College Code", "Place", "College Name", "Branch Name", "Branch code"]
    category_list = [col for col in df.columns if col not in exclusion_list]
    selected_category = st.selectbox("Select Category", ["--Select--"] + sorted(category_list), key="category_select")

    selected_place = st.selectbox(
        "Select Place",
        ["--Select--"] + sorted(df["Place"].dropna().unique()),
        disabled=(selected_category == "--Select--"),
        key="place_select",
    )

# Tabs
tabs = st.tabs(["Branch-Level Options", "College-Level Options"])

# Normal Tab
with tabs[0]:
    col1, col2 = st.columns(2)

    # Add to List
    with col1:
        st.write("### Add to the List")
        if selected_place and selected_place != "--Select--":
            selected_college = st.selectbox(
                "Select College",
                ["--Select--"] + sorted(df[df["Place"] == selected_place]["College Name"].dropna().unique()),
                key="college_select_normal",
            )
            if selected_college and selected_college != "--Select--":
                selected_branch = st.selectbox(
                    "Select Branch",
                    ["--Select--"] + sorted(df[df["College Name"] == selected_college]["Branch Name"].dropna().unique()),
                    key="branch_select_normal",
                )
                if selected_branch and selected_branch != "--Select--":
                    if st.button("Add", key="add_button_normal"):
                        selected_list = [selected_category, selected_place, selected_college, selected_branch]
                        cutoff_rank = getcutoff_rank(selected_list, df)
                        college_code = getcollege_code(selected_list, df)
                        branch_code = getbranch_code(selected_list, df)

                        if cutoff_rank[0] == -1 or college_code == -1 or branch_code == -1:
                            st.error("No data available for the selected options. Please make valid selections.")
                        else:
                            st.success(f"Cutoff Rank for the selected option: {cutoff_rank[0]}")
                            st.session_state["selected_data"].append([college_code, selected_place, selected_college, selected_branch, branch_code, cutoff_rank[1], cutoff_rank[0]])

    # Delete from List
    with col2:
        st.write("### Delete from the List")
        if st.session_state["selected_data"]:
            college_list = list(set([col[2] for col in st.session_state["selected_data"]]))
            selected_college = st.selectbox("Select College", ["--Select--"] + sorted(college_list), key="delete_college")

            if selected_college and selected_college != "--Select--":
                branch_list = [col[3] for col in st.session_state["selected_data"] if col[2] == selected_college]
                selected_branch = st.selectbox(
                    "Select Branch",
                    ["--Select--"] + sorted(branch_list),
                    key="delete_branch",
                )
                if selected_branch and selected_branch != "--Select--":
                    if st.button("Delete", key="delete_button"):
                        st.session_state["selected_data"] = [
                            col for col in st.session_state["selected_data"]
                            if not (col[2] == selected_college and col[3] == selected_branch)
                        ]
                        st.success(f"Deleted {selected_branch} from {selected_college} successfully.")
        else:
            st.write("No colleges available for deletion.")

# College Tab
with tabs[1]:
    col1, col2, col3 = st.columns(3)

    # Add College to List
    with col1:
        st.write("### Add College to the List")
        if selected_place and selected_place != "--Select--":
            selected_college = st.selectbox(
                "Select College",
                ["--Select--"] + sorted(df[df["Place"] == selected_place]["College Name"].dropna().unique()),
                key="college_select_college_tab",
            )
            if st.button("Add College", key="add_college_button"):
                branches = sorted(df[df["College Name"] == selected_college]["Branch Name"].dropna().unique())
                for branch in branches:
                    selected_list = [selected_category, selected_place, selected_college, branch]
                    cutoff_rank = getcutoff_rank(selected_list, df)
                    college_code = getcollege_code(selected_list, df)
                    branch_code = getbranch_code(selected_list, df)
                    if cutoff_rank[0] != -1 and college_code != -1 and branch_code != -1:
                        st.session_state["selected_data"].append([college_code, selected_place, selected_college, branch, branch_code, cutoff_rank[1], cutoff_rank[0]])

    with col2:  # Delete from the list logic
        st.write("### Delete from the List")
        if st.session_state["selected_data"]:
            college_list = list(set([col[2] for col in st.session_state["selected_data"]]))
            selected_college = st.selectbox("Select College", ["--Select--"] + sorted(college_list), key="delete_colg")

            if selected_college and selected_college != "--Select--":
                branch_list = [col[3] for col in st.session_state["selected_data"] if col[2] == selected_college]
                selected_branch = st.selectbox(
                    "Select Branch",
                    ["--Select--"] + sorted(branch_list),
                    key="delete_brah",
                )
                if selected_branch and selected_branch != "--Select--":
                    if st.button("Delete", key="delete_submit"):
                        st.session_state["selected_data"] = [
                            col for col in st.session_state["selected_data"]
                            if not (col[2] == selected_college and col[3] == selected_branch)
                        ]
                        st.success(f"Deleted {selected_branch} from {selected_college} successfully.")
        else:
            st.write("No selections available for deletion.")
    
    # Delete College
    with col3:
        st.write("### Delete the College")
        if st.session_state["selected_data"]:
            college_list = list(set([col[2] for col in st.session_state["selected_data"]]))
            selected_college = st.selectbox("Select College", ["--Select--"] + sorted(college_list), key="delete_all_college")
            if selected_college and selected_college != "--Select--":
                if st.button("Delete All Branches", key="delete_all_button"):
                    st.session_state["selected_data"] = [
                        col for col in st.session_state["selected_data"] if col[2] != selected_college
                    ]
                    st.success(f"All branches of {selected_college} have been deleted successfully.")
        else:
            st.write("No colleges available for deletion.")

# Display Selected Data
if st.session_state["selected_data"]:
    selected_df = gettable(st.session_state["selected_data"])
    st.write("### Selected Colleges and Cutoff Details")
    st.table(selected_df)

    try:
        pdf_path = generate_pdf_table(st.session_state["selected_data"])
        with open(pdf_path, "rb") as pdf_file:
            pdf_data = pdf_file.read()

        st.download_button(
            label="Download as PDF",
            data=pdf_data,
            file_name="colleges_table.pdf",
            mime="application/pdf",
        )
    except ValueError as e:
        st.error(f"Error generating PDF: {e}")
else:
    st.write("### Selected Colleges and Cutoff Details")
    st.table(pd.DataFrame(columns=["College Code", "Place", "College Name", "Branch", "Branch Code", "Category", "Cutoff Rank"])) 
